#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/usr/local/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/usr/local/nrn/i686/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/douglas/Dropbox/epfl/1st-master/neural-networks/miniproject/mod_file_neuron_miniproject/i686/.libs/libnrnmech.so" "$@"
